export type MapTheme = 'forest' | 'village' | 'desert' | 'snow' | 'volcano' | 'space' | 'cyberpunk';

export type AvatarExpression = 'normal' | 'talking' | 'surprised' | 'sweating' | 'laughing';

export type AvatarStyle = {
  id: string;
  name: string;
  emoji: string;
  headwear: string;
  outfit: string;
  color: string;
  badge: string;
  role?: string;
  /** Square portrait crop, for avatar frames. Generated by scripts/crop-avatar-faces.ps1 */
  faceUrl?: string;
  /** Full 2:3 character card, including the name plate and role badge */
  cardUrl?: string;
  expression?: AvatarExpression;
  /** Future progression gate. During the build stage these are visible but free. */
  unlockLevel?: number;
  unlockCost?: number;
};

export type Player = {
  id: string;
  name: string;
  avatar: AvatarStyle;
  score: number;
  /**
   * Epoch ms of this player's last heartbeat. A player who closes the tab stops
   * updating it, which is the only way to tell them apart from someone thinking.
   */
  lastSeen?: number;
  /** Set when they left on purpose, or were dropped for going quiet. */
  connected?: boolean;
  /** Social progression, mostly earned from making the room react. */
  level?: number;
  vibeScore?: number;
  badges?: string[];
  boardPosition: number;
  inventory: string[];
  isHost: boolean;
  isReady: boolean;
  isSpeaking?: boolean;
  ping?: number;
};

export type LanguageCode = 'hausa' | 'igbo' | 'yoruba' | 'pidgin' | 'spanish' | 'french' | 'japanese' | 'korean';

export type ChallengeType = 'language' | 'math' | 'trap';

export type ChallengeWord = {
  id: string;
  word: string;
  phonetic?: string;
  translation?: string;
  language: LanguageCode | 'math' | 'trap';
  type: ChallengeType;
  difficulty: 'easy' | 'medium' | 'hard';
  submittedBy?: string;
};

export type PresetTrap = {
  id: string;
  label: string;
  word: string;
  category: string;
};

export type TrapWord = {
  id: string;
  word: string;
  authorId: string;
  authorName: string;
  targetPlayerId?: string;
  used: boolean;
};

export type EventLog = {
  id: string;
  text: string;
  timestamp: string;
  type: 'buff' | 'debuff' | 'dare' | 'point' | 'system' | 'social';
};

export type PowerupType = 'boost' | 'rewind' | 'shield' | 'dare_gun' | 'freeze' | 'bomb';

export type PowerupItem = {
  id: PowerupType;
  name: string;
  icon: string;
  description: string;
  count: number;
};

export type TileNodeType = 'normal' | 'buff' | 'debuff' | 'dare' | 'mystery' | 'bonus' | 'trap';

export type GamePhase = 'lobby' | 'qualifying_voice' | 'powerup_shop' | 'roadmap_turn' | 'peer_dare' | 'pitch_bird' | 'roast_intermission' | 'game_over';

/** The qualifying mini-games that feed the main board game. */
export type MiniGameId = 'voice_arena' | 'pitch_bird';

/** What a finished mini-game earned the player this turn. */
export type TurnResult = {
  game: MiniGameId;
  /** Points banked, also the currency for the buff shop. */
  pointsEarned: number;
  /** 0..1, normalised across mini-games so they are comparable. */
  performance: number;
  /** Board steps this buys — what the dice will land on. */
  steps: number;
};

/** One player's mini-game result within the current round. */
export type RoundResult = TurnResult & {
  playerId: string;
  playerName: string;
  /** Cleared once they have rolled, so a round cannot be rolled twice. */
  rolled?: boolean;
};

export type SocialReactionId = 'laugh' | 'fire' | 'almost' | 'drama';

export type SocialReaction = {
  id: string;
  reaction: SocialReactionId;
  voterId: string;
  voterName: string;
  targetPlayerId: string;
  timestamp: string;
};

export type JudgeVote = {
  voterId: string;
  voterName: string;
  targetPlayerId: string;
  vote: 'pass' | 'fail';
};

export type SocialRound = {
  targetPlayerId: string;
  reactions: SocialReaction[];
  judgeVotes: JudgeVote[];
};

export type RoomState = {
  roomId: string;
  hostId: string;
  phase: GamePhase;
  players: Player[];
  activePlayerIndex: number;
  selectedLanguages: LanguageCode[];
  mathEnabled: boolean;
  trapWords: TrapWord[];
  currentChallenge: ChallengeWord | null;
  turnTimeLimit: number;
  currentDare: {
    dareText: string;
    targetPlayerId: string;
    challengerPlayerId: string;
    passed?: boolean;
  } | null;
  winner: Player | null;
  theme?: MapTheme;
  events?: EventLog[];
  /** Mini-games the host enabled for this match. */
  enabledMiniGames?: MiniGameId[];
  /** Which mini-game the active player is facing this turn. */
  currentMiniGame?: MiniGameId;
  /** Result of this turn's mini-game, cleared once the player has moved. */
  turnResult?: TurnResult | null;
  /** Laugh meter and peer judge votes for the active voice-related round. */
  socialRound?: SocialRound | null;

  // ── Round-based loop ──────────────────────────────────────────────────────
  // A round is: every player takes the mini-game one at a time, then everyone
  // shops together, then everyone rolls — best mini-game score rolling first.
  roundNumber?: number;
  /** Mini-game results for the round in progress, one per player who has played. */
  roundResults?: RoundResult[];
  /** Player ids in roll order, best mini-game performance first. */
  rollOrder?: string[];
  /** How far through rollOrder the board phase has got. */
  rollIndex?: number;
  /** Players who have finished buying this round. */
  shopReady?: string[];
};
